### ISSUE TITLE
Gradle compiler errors

### ISSUE THREAD

**Issue by WOSAJ** [Anuken/MindustryJavaModTemplate#13] opened 2022-01-31 14:32 UTC
I created a repository using this template, but it doesn't build

https://gist.github.com/WOSAJ/b9cd66d1a00f05b0be51c3f05464c858
Gradle log ^

I have no experience in creating mods.

**Comment by Anuken** [comment] 2022-01-31 14:47
Duplicate of #12

**Closed by Anuken** 2022-01-31 14:47 UTC
